'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, 
  Scan, 
  BookOpen, 
  ChevronRight 
} from 'lucide-react';
import { cn } from '@/lib/utils';
import Image from 'next/image';

const FEATURES = [
  {
    id: 'ai-generation',
    title: 'Geração de Provas com IA',
    description: 'Diga o tema e a série. Nossa IA cria questões inéditas e perfeitamente alinhadas ao conteúdo que você ensinou.',
    icon: Sparkles,
    color: 'bg-purple-500',
    image: '/images/landing/ai-exam-generation.png', // Generated by IA
  },
  {
    id: 'scan-grade',
    title: 'Correção via Câmera',
    description: 'Esqueça as pilhas de papel. Aponte o celular para o gabarito e obtenha a nota instantaneamente.',
    icon: Scan,
    color: 'bg-indigo-500',
    image: '/images/landing/camera-correction.png', // Generated by IA
  },
  {
    id: 'bncc',
    title: 'Alinhamento BNCC',
    description: 'Todas as questões já vêm com os códigos da BNCC. Seus relatórios e planejamentos sempre em dia.',
    icon: BookOpen,
    color: 'bg-teal-500',
    image: '/images/landing/bncc-alignment.png', // Generated by IA
  },
  // {
  //   id: 'analytics',
  //   title: 'Analytics de Turma',
  //   description: 'Identifique quais alunos precisam de reforço e quais tópicos a turma não absorveu bem.',
  //   icon: BarChart3,
  //   color: 'bg-rose-500',
  //   image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2000', // Charts
  // },
];

export function FeaturesGrid() {
  const [activeFeature, setActiveFeature] = useState(0);

  return (
    <section id="features" className="py-24 bg-slate-50">
      <div className="container mx-auto px-4 md:px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl font-display text-slate-900">
            Poder de super-herói para <span className="text-indigo-600">professores</span>
          </h2>
        </div>

        <div className="grid gap-12 lg:grid-cols-2 lg:gap-16 items-center max-w-6xl mx-auto">
          {/* Left: Interactive List */}
          <div className="space-y-4">
            {FEATURES.map((feature, index) => (
              <div
                key={feature.id}
                onClick={() => setActiveFeature(index)}
                className={cn(
                  'group cursor-pointer rounded-2xl p-6 transition-all duration-300 border-2 relative overflow-hidden',
                  activeFeature === index
                    ? 'bg-white border-indigo-600 shadow-lg scale-105'
                    : 'bg-white/50 border-transparent hover:bg-white hover:border-slate-200'
                )}
              >
                <div className="flex items-start gap-4 z-10 relative">
                  <div
                    className={cn(
                      'flex h-12 w-12 shrink-0 items-center justify-center rounded-xl transition-colors duration-300',
                      activeFeature === index 
                        ? `${feature.color} text-white` 
                        : 'bg-slate-100 text-slate-500 group-hover:bg-slate-200'
                    )}
                  >
                    <feature.icon className="h-6 w-6" />
                  </div>
                  <div className="flex-1">
                    <h3
                      className={cn(
                        'text-lg font-bold mb-1 transition-colors',
                        activeFeature === index ? 'text-slate-900' : 'text-slate-600'
                      )}
                    >
                      {feature.title}
                    </h3>
                    <p className="text-sm text-slate-500 leading-relaxed">
                      {feature.description}
                    </p>
                  </div>
                  <ChevronRight 
                    className={cn(
                      "h-5 w-5 text-slate-300 transition-all duration-300 self-center",
                      activeFeature === index ? "text-indigo-600 translate-x-1" : "opacity-0 group-hover:opacity-100"
                    )} 
                  />
                </div>
              </div>
            ))}
          </div>

          {/* Right: Dynamic Image Preview */}
          <div className="relative aspect-[4/3] lg:aspect-square rounded-3xl overflow-hidden bg-white shadow-2xl border border-slate-100 ring-1 ring-slate-900/5">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeFeature}
                initial={{ opacity: 0, scale: 1.05 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.4 }}
                className="absolute inset-0"
              >
                <Image
                  src={FEATURES[activeFeature].image}
                  alt={FEATURES[activeFeature].title}
                  fill
                  className="object-cover"
                />
                {/* Overlay for better text contrast if needed, mostly decoration here */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent opacity-60" />
                
                <div className="absolute bottom-0 left-0 p-8 text-white">
                  <div className={cn("inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-white/20 backdrop-blur-md border border-white/30 mb-3")}>
                    {(() => {
                      const Icon = FEATURES[activeFeature].icon;
                      return <Icon className="w-3 h-3 mr-2" />;
                    })()}
                    Feature em Destaque
                  </div>
                  <h4 className="text-2xl font-bold">{FEATURES[activeFeature].title}</h4>
                </div>
              </motion.div>
            </AnimatePresence>
          </div>
        </div>
      </div>
    </section>
  );
}
